### ISSUE TITLE
About the test code

### ISSUE THREAD

**Issue by wangli000** [RammusLeo/DPMesh#5]
hi， thanks for your job, i wonder how i can test this model for in the wild img. i only want to use this pipeline for my data to do mesh recovery instead of evaluation on datasets, do you have the code for test and redner? thanks again!

**Comment by RammusLeo** [comment]
Thanks for your interests! We've update the codes for test and rendering. you can follow steps in [5. Rendering](https://github.com/RammusLeo/DPMesh?tab=readme-ov-file#-5-rendering) to render the multi-person videos. Hope these code can help you!

**Comment by wangli000** [comment]
thanks for your reply！this is amazing work，and i also wonder to know when to realse the training code？i will appreciate it if you reply to me again！
--------------原始邮件--------------
发件人："Ao&nbsp;Li ***@***.***&gt;;
发送时间：2024年7月13日(星期六) 中午1:04
收件人："RammusLeo/DPMesh" ***@***.***&gt;;
抄送："Li Wang ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [RammusLeo/DPMesh] About the test code (Issue #5)
-----------------------------------

 

 
Thanks for your interests! We've update the codes for test and rendering. you can follow steps in 5. Rendering to render the multi-person videos. Hope these code can help you!

**Comment by Jilin-Cancer** [comment]
Hi， thanks for your job. When I was following the readme steps for Evaluation, I had the following problems:
Traceback (most recent call last):
File "eval.py", line 7, in <module>
from common.base import Trainer
File "/data/hjl/code/DPMesh-main/common/base.py", line 27, in <module>
exec('from dataloader.' + dataset_list[i] + ' import ' + dataset_list[i])
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'dataloader.CrowdPose_v2'


dataloader only has 'CrowdPose', Human36M', My_MSCOCO', My_MuCo', and PW3D'.  Is there any _v2 file missing?

**Comment by RammusLeo** [comment]
> Hi， thanks for your job. When I was following the readme steps for Evaluation, I had the following problems: Traceback (most recent call last): File "eval.py", line 7, in from common.base import Trainer File "/data/hjl/code/DPMesh-main/common/base.py", line 27, in exec('from dataloader.' + dataset_list[i] + ' import ' + dataset_list[i]) File "", line 1, in ModuleNotFoundError: No module named 'dataloader.CrowdPose_v2'
> 
> dataloader only has 'CrowdPose', Human36M', My_MSCOCO', My_MuCo', and PW3D'. Is there any _v2 file missing?

Sorry for doubts. I use prefix like "My_" or suffix like "v2" to differentiate my dataloaders in my local code base. You may just remove them so that they can match the file names in `/dataloader`

**Comment by Jilin-Cancer** [comment]
Thanks for your answer, in order to run eval, I changed base.py to dataset_list = ['PW3D'], preparing only 3DPW data as described in the readme. But I'm running:  CUDA_VISIBLE_DEVICES=0 torchrun --master_port 29591 --nproc_per_node 1 eval.py --cfg ./configs/main_train.yml  --exp_id="main_train" --distributed
There is a problem:
Traceback (most recent call last):
File "eval.py", line 275, in <module>
main()
File "eval.py", line 93, in main
trainer._make_model(is_eval=True)
File "/data/hjl/code/DPMesh-main/common/base.py", line 173, in _make_model
model = get_model(self.joint_num, 'train', self.cfg)
File "/data/hjl/code/DPMesh-main/common/model.py", line 304, in get_model
cldm = VPDEncoder()
File "/data/hjl/code/DPMesh-main/common/vpd/vpdencoder_useattn.py", line 36, in __init__
self.sd_model = create_model('./common/vpd/cldm_v15.yaml').cpu()
File "/data/hjl/code/DPMesh-main/cldm/model.py", line 26, in create_model
model = instantiate_from_config(config.model).cpu()
File "/data/hjl/code/DPMesh-main/ldm/util.py", line 79, in instantiate_from_config
return get_obj_from_str(config["target"])(**config.get("params", dict()))
File "/data/hjl/code/DPMesh-main/cldm/cldm.py", line 541, in __init__
super().__init__(*args, **kwargs)
File "/data/hjl/code/DPMesh-main/ldm/models/diffusion/ddpm.py", line 565, in __init__
self.instantiate_cond_stage(cond_stage_config)
File "/data/hjl/code/DPMesh-main/ldm/models/diffusion/ddpm.py", line 632, in instantiate_cond_stage
model = instantiate_from_config(config)
File "/data/hjl/code/DPMesh-main/ldm/util.py", line 79, in instantiate_from_config
return get_obj_from_str(config["target"])(**config.get("params", dict()))
File "/data/hjl/code/DPMesh-main/ldm/modules/encoders/modules.py", line 99, in __init__
self.tokenizer = CLIPTokenizer.from_pretrained(version)
The File "/ home/HJL /. Conda/envs/dpmesh/lib/python3.8 / site - packages/transformers/tokenization_utils_base. Py", line 1785, in from_pretrained
raise EnvironmentError(
OSError:  Can't load tokenizer for 'clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models',  make sure you don't have a local directory with the same name. Otherwise,  make sure 'clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer  tokenizer.
I have read the operation in readme that does not need to download clip-vit-large-patch14, looking forward to your answer
